@startuml system-context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

' Entities
Person(pet_owner, "Pet Owner")
System(pet_feeding_platform, "Pet Feeding Platform", "Allows pet owners to store information related to the feeding of their pet(s)")
System_Ext(pet_data_store, "Pet Data Store", "Stores the information about the pet(s) of an pet owner")

' Relations
Rel(pet_owner, pet_feeding_platform, "Configure feeding details of pet")

Rel(pet_feeding_platform, pet_owner, "Send feeding reminder")
Rel(pet_feeding_platform, pet_data_store, "Retrieve pet details")

@enduml